### PR TITLE
Branch fix import command

### LINKED ISSUE #143: [Import] Fix bugs and update tests

### PR DESCRIPTION
**Pull request by Hoodini231**
fixes #143

### CODE REVIEW

**Comment by Hoodini231** [comment]
NOTE: Due to name being the primary key I made it so if it is empty it simply produces a data is corrupted error as a name is required for import to work flawlessly

File: src/main/java/seedu/address/logic/commands/ImportCommand.java [hunk 1]
```diff
@@ -34,30 +34,25 @@
...
+    public static final String MESSAGE_SUCCESS = "Data imported. \n%d students imported.";
     public static final String MESSAGE_USAGE = COMMAND_WORD
         + ": Imports the data from a csv file.\n"
-        + "Parameters: import file path\n"
+        + "Parameters: import <absolute file path>\n"
         + "Example: " + COMMAND_WORD
         + " /Users/username/Desktop/addressbook.csv";
 
-
     private static final Path projectRootPath = Paths.get(System.getProperty("user.dir"));
```
Comment (wenjebs) [inline src/main/java/seedu/address/logic/commands/ImportCommand.java:53]: looks good! good to be explicit

File: src/main/java/seedu/address/logic/commands/ImportCommand.java [hunk 2]
```diff
@@ -69,47 +64,52 @@ public ImportCommand(Path importCsvFilePath) {
...
     }
 
     @Override
     public CommandResult execute(Model model) throws CommandException {
         requireNonNull(model);
         requireNonNull(importCsvFilePath);
         requireNonNull(storage);
-        readCsvFile(model);
-        return new CommandResult(MESSAGE_SUCCESS);
+        int studentsImported = readCsvFile(model);
```
Comment (yimjianbing) [inline src/main/java/seedu/address/logic/commands/ImportCommand.java:74]: Maybe since now readCsvFile returns an int, its name should be changed to getImportedStudents, to reflect its purpose better and to prevent ambiguity

File: src/main/java/seedu/address/logic/commands/ImportCommand.java [hunk 3]
```diff
@@ -69,47 +64,52 @@ public ImportCommand(Path importCsvFilePath) {
...
+        return new CommandResult(String.format(MESSAGE_SUCCESS, studentsImported));
     }
 
     /*
      * Reads the CSV file and imports the data into the address book
      */
-    private void readCsvFile(Model model) throws CommandException {
+    private int readCsvFile(Model model) throws CommandException {
```
Comment (yimjianbing) [inline src/main/java/seedu/address/logic/commands/ImportCommand.java:81]: Actually do you think its better to split this method into two, one for reading, one for getting tihe mportedStudent

File: src/main/java/seedu/address/logic/commands/ImportCommand.java [hunk 4]
```diff
@@ -119,15 +119,48 @@ private void readCsvFile(Model model) throws CommandException {
...
+            message += String.format("Data imported with %d students added.", importStudentNumbers[0]);
+        }
+
+        if (importStudentNumbers[1] > 0) {
+            message += String.format("\n%d Duplicate person(s) found in file: %s",
+                importStudentNumbers[1],
+                duplicatePersonsNames.toString());
+        }
+        return message;
+    }
```
Comment (yimjianbing) [inline src/main/java/seedu/address/logic/commands/ImportCommand.java:144]: Remember to add junit test for this method!

File: src/test/java/seedu/address/logic/commands/ImportCommandTest.java [hunk 5]
```diff
@@ -4,8 +4,13 @@
 import static org.junit.jupiter.api.Assertions.assertNotEquals;
 import static seedu.address.testutil.Assert.assertThrows;
 import static seedu.address.testutil.TypicalPaths.DUPLICATE_IMPORT_FILE;
+import static seedu.address.testutil.TypicalPaths.EMPTY_IMPORT_FILE;
 import static seedu.address.testutil.TypicalPaths.INVALID_IMPORT_FILE;
+import static seedu.address.testutil.TypicalPaths.INVALID_MISSING_NAME_FILE;
+import static seedu.address.testutil.TypicalPaths.VALID_MISSING_CLASS_FILE;
 import static seedu.address.testutil.TypicalPaths.VALID_MISSING_DATA_IMPORT_FILE;
+import static seedu.address.testutil.TypicalPaths.VALID_MISSING_PHONE_FILE;
+import static seedu.address.testutil.TypicalPaths.VALID_MISSING_TAGS_FILE;
```
Comment (yimjianbing) [inline src/test/java/seedu/address/logic/commands/ImportCommandTest.java:13]: Great usage of the TypicalPaths constants!

**Review by yimjianbing — CHANGES_REQUESTED** [review]
LGTM! other than the misnamed readCsvFile method

File: src/main/java/seedu/address/logic/commands/ImportCommand.java (hunk 3 above)
Comment (Hoodini231) [reply src/main/java/seedu/address/logic/commands/ImportCommand.java:81]: I think this would cause unnecessary code and duplicate code, thus it wouldn't be beneficial

File: src/main/java/seedu/address/logic/commands/ImportCommand.java (hunk 2 above)
Comment (Hoodini231) [reply src/main/java/seedu/address/logic/commands/ImportCommand.java:74]: excellent point! I'll fix it asap

File: src/main/java/seedu/address/logic/commands/ImportCommand.java [hunk 6]
```diff
@@ -71,14 +71,18 @@ public CommandResult execute(Model model) throws CommandException {
...
-     * Reads the CSV file and imports the data into the address book
+    /**
+     * Method that reads the csv file and adds students to the model
+     * Returns the number of students imported as well
+     * @param model
+     * @return int
+     * @throws CommandException
      */
-    private int readCsvFile(Model model) throws CommandException {
+    private int addStudentsFromCsv(Model model) throws CommandException {
```
Comment (yimjianbing) [inline src/main/java/seedu/address/logic/commands/ImportCommand.java:85]: Great work! Really appreciate the changes made

**Review by yimjianbing — APPROVED** [review]
