### PR TITLE
Fix bug in AddressBookParser

### LINKED ISSUE #161: [ConsecutiveCommand] Cannot run Delete and Help command consecutively

### PR DESCRIPTION
**Pull request by Hoodini231**
Fixes #161

### CODE REVIEW

File: src/main/java/seedu/address/logic/parser/AddressBookParser.java [hunk 1]
```diff
@@ -64,7 +64,8 @@ public Command parseCommand(String userInput) throws ParseException {
         logger.fine("Command word: " + commandWord + "; Arguments: " + arguments);
 
         // Check if the command is consecutive
-        if (commandWord.equals(lastCommandWord) & arguments.equals(lastArgument)) {
+        if (commandWord.equals(lastCommandWord) & arguments.equals(lastArgument)
+            && !commandWord.equals("delete") && !commandWord.equals("help")) {
```
Comment (martout2002) [inline src/main/java/seedu/address/logic/parser/AddressBookParser.java:68]: thanks for catching this bug!

**Review by martout2002 — APPROVED** [review]
LGTM
